name: Push Pipeline with Timeout

on: [push]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true #It cancel running one and pick up latest one

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # ⏱️ job timeout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Building..."
          sleep 30

      - name: Test step (timeout demo)
        timeout-minutes: 1   # ⏱️ step timeout
        run: |
          echo "Running tests..."
          sleep 300

      - name: Finish
        run: echo "Pipeline completed"