name: conditions
on: [push]
jobs:
  conditions-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello, World!"

      - name: trigger main
        if: github.ref == 'refs/heads/main'
        run: echo "Runs only on main branch"